FROM continuumio/anaconda3:4.4.0
MAINTAINER UNP, https://unp.education
COPY ./flask_demo /Users/shuyuej/Desktop/python-docker/
EXPOSE 5000
WORKDIR /Users/shuyuej/Desktop/python-docker/
RUN pip install -r requirements.txt
CMD python test.py
